import type { NextConfig } from "next";

function publicEnv(nextPublicName: string, viteName: string) {
  return process.env[nextPublicName] || process.env[viteName] || "";
}

const nextConfig: NextConfig = {
  env: {
    NEXT_PUBLIC_FIREBASE_API_KEY: publicEnv("NEXT_PUBLIC_FIREBASE_API_KEY", "VITE_FIREBASE_API_KEY"),
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: publicEnv("NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN", "VITE_FIREBASE_AUTH_DOMAIN"),
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: publicEnv("NEXT_PUBLIC_FIREBASE_PROJECT_ID", "VITE_FIREBASE_PROJECT_ID"),
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: publicEnv(
      "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
      "VITE_FIREBASE_STORAGE_BUCKET"
    ),
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: publicEnv(
      "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
      "VITE_FIREBASE_MESSAGING_SENDER_ID"
    ),
    NEXT_PUBLIC_FIREBASE_APP_ID: publicEnv("NEXT_PUBLIC_FIREBASE_APP_ID", "VITE_FIREBASE_APP_ID"),
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: publicEnv(
      "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID",
      "VITE_FIREBASE_MEASUREMENT_ID"
    )
  }
};

export default nextConfig;
